### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by IvoLeal72** [BastouP411/bperipherals#1]
Can you please add a keyboard for computers in this mod? There are no other peripherals mod for 1.15.2, and it would be very usefull, thanks for the attention

**Comment by BastouP411** [comment]
What would the keyboard do ? There is no such things as keyboards in ComputerCraft.

**Comment by LoyaltyGamer72** [comment]
It would be assigned to a computer and basically let you type in that computer without seing its gui, would be usefull with monitors, i will send you 2 implementations in other mods for older minecraft versions:
https://squiddev-cc.github.io/plethora/items/keyboard.html
https://github.com/theoriginalbit/MoarPeripherals/wiki/Keyboard

**Comment by LoyaltyGamer72** [comment]
Any news on this? Are there gonna be a keyboard added to the mod?

**Comment by BastouP411** [comment]
Hey ! I finally had the time to implement this.
Added in https://github.com/BastouP411/bperipherals/commit/353c504d54b5bd9311492356b88f70d408555d2e.

**Comment by BastouP411** [comment]
Closing request ;)
