### ISSUE TITLE
Feature Request: Add an extra optional boolean parameter to the (Mag Card Reader).write method

### ISSUE THREAD

**Issue by GamesArsenal96** [BastouP411/bperipherals#3]
**_Feature Request_**

Add the ability to set a optional boolean parameter to the write method on the Mag Card Reader/Writer

**`write(data,secure)`**
'secure' would be default to True
Would allow you to disable ByteArray encryption from your Mag Cards.

I have been trying to implement this myself but sadly not working because the parameter gets set to a String type when data is written.
<Line 36>: `BPeripherals/src/main/java/fr/bastoup/bperipherals/peripherals/magcardreader/PeripheralMagCardReader.java`
![eclipse_20-01-37-34{AM}](https://user-images.githubusercontent.com/24835664/108587950-4216c880-731c-11eb-8dbe-c9a2cb3e0314.png)

<Line 87>: `BPeripherals/src/main/java/fr/bastoup/bperipherals/peripherals/magcardreader/TileMagCardReader.java`
![eclipse_20-01-32-10{AM}](https://user-images.githubusercontent.com/24835664/108587813-86ee2f80-731b-11eb-9348-1709450c7d7c.png)

![Code_20-01-14-04{AM}](https://user-images.githubusercontent.com/24835664/108587444-2bbb3d80-7319-11eb-9c08-3ec1dedac331.png)
![javaw_20-01-13-50{AM}](https://user-images.githubusercontent.com/24835664/108587446-2eb62e00-7319-11eb-9e21-9bb852fed481.png)

**Comment by GamesArsenal96** [comment]
Maybe you can show me how to get it to work or implement it yourself :3

**Comment by BastouP411** [comment]
> **_Feature Request_**
> 
> 
> 
> Add the ability to set a optional boolean parameter to the write method on the Mag Card Reader/Writer
> 
> 
> 
> **`write(data,secure)`**
> 
> 'secure' would be default to True
> 
> Would allow you to disable ByteArray encryption from your Mag Cards.

This is not an encryption. Strings in CC are encoded using a specific encoding (not utf-8ascii, or anything). So to prevent problems with encoding on the transition with java I get and store the string as a byte buffer/array on the card item. This however has no influence on the way the peripheral works.

**Comment by GamesArsenal96** [comment]
> > **_Feature Request_**
> > Add the ability to set a optional boolean parameter to the write method on the Mag Card Reader/Writer
> > **`write(data,secure)`**
> > 'secure' would be default to True
> > Would allow you to disable ByteArray encryption from your Mag Cards.
> 
> This is not an encryption. Strings in CC are encoded using a specific encoding (not utf-8ascii, or anything). So to prevent problems with encoding on the transition with java I get and store the string as a byte buffer/array on the card item. This however has no influence on the way the peripheral works.

I know it works the same normally in CC but in the actual itemTag.data it shows in bytes which makes it secure from nbt readers wanted the option for having that back to a normal string when the secure param is set to false. I already coded it so it shows as a normal string again but it won't go back to a ByteBuffer if set to true. so rn I just removed it turning into bytes and it shows as a normal string so I can pass tables through it for more flexibility

**Comment by BastouP411** [comment]
> I know it works the same normally in CC but in the actual itemTag.data it shows in bytes which makes it secure from nbt readers, I wanted the option for having that back to a normal string when the secure param is set to false. I already coded it so it shows as a normal string again but it won't go back to a ByteBuffer if set to true. so rn I just removed it turning into bytes and it shows as a normal string so I can pass tables through it for more flexibility

I don't think this is a good addition for 2 main reasons:
 1. It is much easier and safer to handle bytes instead of Strings (due to the conversion)
 2. It is a magnetic card, the data on the card cannot be read without the reader.

However, another NBT tag could be added, being a label for the card.

**Comment by BastouP411** [comment]
@GamesArsenal96 
Fixed with https://github.com/BastouP411/bperipherals/commit/d6127dbfa10e11e022901ac19e6ad72e477c3b06
