### ISSUE TITLE
Enhancement to Wiki: We need more info about the database

### ISSUE THREAD

**Issue by GamesArsenal96** [BastouP411/bperipherals#4]
We need more info about the database, it seems like a VERY interesting block but I have no idea how to use it

**Comment by BastouP411** [comment]
> We need more info about the database, it seems like a VERY interesting block but I have no idea how to use it

It uses the SQL language. Maybe it isn't clear in the wiki. Some other WIP features are already present, but not documented yet (help for table creation, etc. etc. )

**Comment by BastouP411** [comment]
@GamesArsenal96 I added more information in the wiki.

**Comment by GamesArsenal96** [comment]
> @GamesArsenal96 I added more information in the wiki.

Thank you sooo much :3!

Also can you share some examples?

**Comment by BastouP411** [comment]
> Also can you share some examples of CC usage?

Yeah I plan to do it in a near future ^^

**Comment by GamesArsenal96** [comment]
> > Also can you share some examples of CC usage?
> 
> Yeah I plan to do it in a near future ^^

**Comment by BastouP411** [comment]
Closing this issue. Thank you ^^
