### ISSUE TITLE
[FEATURE] Allow to get mag card data and write new on the same swipe.

### ISSUE THREAD

**Issue by LoyaltyGamer72** [BastouP411/bperipherals#5]
It would be cool if the mag_write event would return the data previously on the card or both 'mag_swipe' and 'mag_write' events fired.
I know this feels useless, and can easily get worked arround, but i wanted to register how many times the card was used, or for an one use ticket system, stored on the card. I'm the only one on my friends server that knwo how to use computercraft and this would make things easier than sharing info between computers to knwo that the card has been used.

**Comment by BastouP411** [comment]
> It would be cool if the mag_write event would return the data previously on the card or both 'mag_swipe' and 'mag_write' events fired.
> I know this feels useless, and can easily get worked arround, but i wanted to register how many times the card was used, or for an one use ticket system, stored on the card. I'm the only one on my friends server that knwo how to use computercraft and this would make things easier than sharing info between computers to knwo that the card has been used.

Wow sorry, I didn't see the notification. I already thought about it, and I'm probably going to implement it.

**Comment by BastouP411** [comment]
@LoyaltyGamer72 
Fixed with https://github.com/BastouP411/bperipherals/commit/5625ad87309daf0365ac57fd106f9eb6bcfc0e59

**Comment by LoyaltyGamer72** [comment]
Can you please publish or send me the compiled version with the update, I really need it for a system on my server 😊😊 I would compile too but I believe I need instructions on how to do it.

**Comment by BastouP411** [comment]
@LoyaltyGamer72  Sorry I do not have time yet to update it. Going through lots of exams.
Ifr you want to build it yourself you'd have to run `./gradlew build`

**Comment by LoyaltyGamer72** [comment]
Already tried in my ubuntu machine it errored, I will try on my windows machine and see if it works

**Comment by LoyaltyGamer72** [comment]
same error...

Downloading https://services.gradle.org/distributions/gradle-4.10.3-bin.zip
..........................................................................
Unzipping C:\Users\ivogc\.gradle\wrapper\dists\gradle-4.10.3-bin\31t79e2qsceia4mkbojplrgx\gradle-4.10.3-bin.zip to C:\Users\ivogc\.gradle\wrapper\dists\gradle-4.10.3-bin\31t79e2qsceia4mkbojplrgx

Welcome to Gradle 4.10.3!

Here are the highlights of this release:
 - Incremental Java compilation by default
 - Periodic Gradle caches cleanup
 - Gradle Kotlin DSL 1.0-RC6
 - Nested included builds
 - SNAPSHOT plugin versions in the `plugins {}` block

For more details see https://docs.gradle.org/4.10.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Java: 15 JVM: 15+36-1562(Oracle Corporation) Arch: amd64
New Dep: net.minecraftforge:forge:1.16.4-35.1.16_mapped_snapshot_20201028-1.16.3

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'bperipherals'.
> Could not resolve all files for configuration ':_compileJava_1'.
   > Could not find patchy.jar (com.mojang:patchy:1.1).
     Searched in the following locations:
         https://files.minecraftforge.net/maven/com/mojang/patchy/1.1/patchy-1.1.jar
   > Could not find oshi-core.jar (oshi-project:oshi-core:1.1).
     Searched in the following locations:
         https://files.minecraftforge.net/maven/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
   > Could not find javabridge.jar (com.mojang:javabridge:1.0.22).
     Searched in the following locations:
         https://files.minecraftforge.net/maven/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
   > Could not find brigadier.jar (com.mojang:brigadier:1.0.17).
     Searched in the following locations:
         https://files.minecraftforge.net/maven/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
   > Could not find datafixerupper.jar (com.mojang:datafixerupper:4.0.26).
     Searched in the following locations:
         https://files.minecraftforge.net/maven/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
   > Could not find authlib.jar (com.mojang:authlib:2.1.28).
     Searched in the following locations:
         https://files.minecraftforge.net/maven/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
   > Could not find text2speech.jar (com.mojang:text2speech:1.11.3).
     Searched in the following locations:
         https://files.minecraftforge.net/maven/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
   > Could not find text2speech-natives-windows.jar (com.mojang:text2speech:1.11.3).
     Searched in the following locations:
         https://files.minecraftforge.net/maven/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 14s

**Comment by BastouP411** [comment]
@LoyaltyGamer72 published on curseforge in last update !
