### ISSUE TITLE
[FEATURE] Configurable options

### ISSUE THREAD

**Issue by Asmoyed** [BastouP411/bperipherals#6]
# Description
Currently with the mag card reader thingy you can only write 32 characters, I would like to be able to expand that limit.
# Possible solution
Adding a config file (server side) could be a solution to this.

---
Thanks ^^

**Comment by BastouP411** [comment]
> # Description
> 
> Currently with the mag card reader thingy you can only write 32 characters, I would like to be able to expand that limit.
> 
> # Possible solution
> 
> Adding a config file (server side) could be a solution to this.
> 
> 
> 
> ---
> 
> Thanks ^^
> 
> 
> 
>  
> 
> 

Already implemented in dev ^^

**Comment by BastouP411** [comment]
@Asmoyed published on curseforge in last update !

**Comment by Asmoyed** [comment]
Thanks ^^
