### ISSUE TITLE
[FEATURE] Fabric Port to CC:R

### ISSUE THREAD

**Issue by Merith-TK** [BastouP411/bperipherals#7]
I am mainly asking this as i would love to see mods that support/add blocks that act as peripherals to CC:R, 

The hardest part about porting in this mods current state is block registration and player interactions as we did our best to keep the peripheral code 1:1 with CC:T

**Comment by BastouP411** [comment]
@Merith-TK I don't know anything about Fabric. It would definitely be an update worth thinking about, however I am currently completely unable to do it.

**Comment by Merith-TK** [comment]
No worries. Just figured atleast this could be useful for you!

https://github.com/Toad-Dev/cc-peripheral-test

This is an example peripheral containing a single block that can be used for both peripheral and turtle upgrade.

It also shows how to register and assign a block texture in fabric so that's the complicated stuff dealt with,

The most difficult part if you forked the repo I linked, would be player interactions,

And the  all that's left is to make sure that the code does work as intended.

I personally don't know much about minecraft modding when it comes to code (yet) but it shouldn't be terribly difficult thanks to the example mod.

**Comment by BastouP411** [comment]
Hello ! I thought about it for some time, and I probably won't do this myself. Sorry, I do not even have enough time to maintain the forge version ^^

**Comment by BastouP411** [comment]
Closing this :)
