### ISSUE TITLE
[FEATURE] Memory limit of database disk.

### ISSUE THREAD

**Issue by MAGGen-hub** [BastouP411/bperipherals#8]
Well I gess we still need more info about database... 
Did database disk has any memory limit? And how can I get it if it exists...
I want to run your mod no server so that why I asked that... 
If DB disk has no memory limit I am more than sure that someone tries to shutdown the server overloading the memory with useless stuff in DB disk... 

Please add the info about memory limit on wiki or add memory limit for your disks if it not exists (like for the normal floppy disk (125KB or more but no more than 1MB))...

**Comment by BastouP411** [comment]
The db disk has a size limit tha can be configured in the server config file :)

**Comment by MAGGen-hub** [comment]
Whops... Sorry... Silly me... But I still have a question... How can I get the remaining memory on disk (it's size I mean)... I need to use the SQL request?
Thanks for answer and please add this info (about config file) to wiki with BIG fontt for dump persons like me... Sorry for silly question)

**Comment by BastouP411** [comment]
I'll add it in the wiki ^^
I am using the SQLite pragma to limit the file size. I don't know if there is a function to know the space taken, sorry :(

**Comment by MAGGen-hub** [comment]
Also that means that users can edit this file not only with SQL but manualy (I mean change some bytes in db)...

**Comment by MAGGen-hub** [comment]
found it: fs.getSize(path) the method you can use in CC to get the file size just put a link to the file to the PC folder)

**Comment by MAGGen-hub** [comment]
Or... Well why not to leave that like it was now... I mean what if user create the script that collects all data from db to calculate it size?

**Comment by MAGGen-hub** [comment]
I got some info about PRAGMA. You need to get PRAGMA PAGE_SIZE and PRAGMA PAGE_COUNT then multiply it and you will get the size of db)

**Comment by MAGGen-hub** [comment]
FINALY!!! THIS IS MY CURRENT SIZE!!! Add this to wiki in (HOW TO GET THE SIZE) selection. See the screenshot my base current size is 1024*2 = 2048 just as I said in last comment) Thanks for helping this issue can be closed now. Hope I helped you too)

Now you can see the way to get current size of db in lua. I will search how to find the way to get max size of db (I more than sure pragma has other interesting comands)

![image](https://user-images.githubusercontent.com/56871670/139944059-611adcfd-7a93-4b1c-8877-3ac5fd16fd98.png)

**Comment by BastouP411** [comment]
Changed wiki entry. Closing issue.
