### ISSUE TITLE
a way to use peripheral.find() for all the blocks

### ISSUE THREAD

**Issue by Ai-Kiwi** [BastouP411/bperipherals#9]
Title sums it up quite well. I'm not sure if I'm just not spelling it right or something but I seem to have tried everything.

**Comment by Mathilde411** [comment]
@Ai-Kiwi I'm not really shure what you mean ?
peripheral.find() is made to find peripherals, could you tell me a bit more ?

**Comment by Ai-Kiwi** [comment]
ok so I want to find the crypto peripheral using it but I can find the right string if there is one to find it? or is the cryptographic accelerator not a peripheral?

**Comment by Mathilde411** [comment]
@Ai-Kiwi the cryptographic accelerator is indeed a peripheral. Did you try `peripheral.find("cryptographic_accelerator")` ?

**Comment by Mathilde411** [comment]
As seen [here](https://github.com/BastouP411/bperipherals/blob/master/src/main/java/fr/bastoup/bperipherals/peripherals/cryprographicaccelerator/PeripheralCryptographicAccelerator.java), the type of the peripheral is `cryptographic_accelerator`, so you should be able to find one using the sythax above ^^

**Comment by Ai-Kiwi** [comment]
huh I'm dumb so when I was testing the block for the write string I somewhere along the line removed the block to get the spelling right so err no crap it didn't work. thanks for help!

**Comment by Mathilde411** [comment]
@Ai-Kiwi you're welcome ^^
